# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V_RtGL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1450, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1450, 730))
        Form.setMaximumSize(QtCore.QSize(1450, 730))
        Form.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1451, 730))
        self.widget_2.setObjectName("widget_2")
        self.Head = QtWidgets.QWidget(self.widget_2)
        self.Head.setGeometry(QtCore.QRect(170, 0, 1280, 40))
        self.Head.setStyleSheet("background-color: rgb(21, 21, 21);")
        self.Head.setObjectName("Head")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Head)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.pushButton_13 = QtWidgets.QPushButton(self.Head)
        self.pushButton_13.setGeometry(QtCore.QRect(1240, 0, 40, 40))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Bold")
        font.setPointSize(20)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);;background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 85, 0, 240);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.Head)
        self.pushButton_15.setGeometry(QtCore.QRect(1160, 0, 40, 40))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Bold")
        font.setPointSize(20)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_14 = QtWidgets.QPushButton(self.Head)
        self.pushButton_14.setGeometry(QtCore.QRect(1200, 0, 40, 40))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Bold")
        font.setPointSize(20)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(170, 0, 1280, 730))
        self.label_3.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"background-image: url(:/新前缀/开始游戏.png);\n"
"background-repeat:no-repeat;\n"
"    color: rgb(85, 0, 0);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-image: url(:/新前缀/开始游戏_b.png);\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:/Star Rail/bg/e1d5adb73c210d050814512cc94c6a2a_5773437140068638718.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(1380, 40, 71, 691))
        self.widget_4.setStyleSheet("QWidget{\n"
"    background-color: rgba(1, 1, 9, 50);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setGeometry(QtCore.QRect(17, 43, 40, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/蕉游shit.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/蕉游shit_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_2.setGeometry(QtCore.QRect(17, 110, 40, 40))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/慰性.png);}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/慰性_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setGeometry(QtCore.QRect(17, 176, 40, 40))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"background-image: url(:/新前缀/厕所.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/厕所_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_4.setGeometry(QtCore.QRect(17, 243, 40, 40))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/wike-1.png);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/wike-1_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setGeometry(QtCore.QRect(17, 310, 40, 40))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/QIt群.png);}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/QIt群_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_6.setGeometry(QtCore.QRect(17, 377, 40, 40))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/inf_a.png);}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    \n"
"    background-image: url(:/新前缀/inf_a_b.png);\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setGeometry(QtCore.QRect(17, 444, 40, 40))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{border-radius: 20px; background-color: rgba(0, 0, 0, 154);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;background-image: url(:/新前缀/VR_inf.png);}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #FF0000;\n"
"    background-image: url(:/新前缀/VR_inf_b.png);\n"
"\n"
"    border-color: rgb(6, 160, 255);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(225, 235, 460, 213))
        self.widget_5.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(225, 465, 460, 120))
        self.widget_6.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.widget_6.setObjectName("widget_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_11.setGeometry(QtCore.QRect(1076, 610, 211, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("HYWenHei")
        font.setPointSize(17)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"background-image: url(:/新前缀/开始游戏.png);\n"
"background-repeat:no-repeat;\n"
"    color: rgb(85, 0, 0);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(85, 55, 55);\n"
"    background-image: url(:/新前缀/开始游戏_b.png);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_12.setGeometry(QtCore.QRect(1280, 610, 41, 71))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:center;\n"
"background-image: url(:/新前缀/本地文件管理.png);\n"
"background-repeat:no-repeat\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-image: url(:/新前缀/本地文件管理_b.png);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.left_control = QtWidgets.QFrame(self.widget_2)
        self.left_control.setGeometry(QtCore.QRect(0, 0, 170, 730))
        self.left_control.setStyleSheet("QFrame{\n"
"    ;\n"
"    background-color: rgba(0, 227, 189, 100);\n"
"}")
        self.left_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_control.setObjectName("left_control")
        self.label_7 = QtWidgets.QLabel(self.left_control)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.left_control)
        self.widget.setGeometry(QtCore.QRect(0, 40, 170, 310))
        self.widget.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.widget.setObjectName("widget")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"border-bottom: 2px solid;border-bottom-color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.SR = QtWidgets.QPushButton(self.widget)
        self.SR.setGeometry(QtCore.QRect(0, 40, 85, 90))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(13)
        self.SR.setFont(font)
        self.SR.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SR.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;background-image: url(:/新前缀/蕉游shit_b.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.SR.setObjectName("SR")
        self.GEN = QtWidgets.QPushButton(self.widget)
        self.GEN.setGeometry(QtCore.QRect(85, 40, 85, 90))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(16)
        self.GEN.setFont(font)
        self.GEN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.GEN.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;background-image: url(:/新前缀/蕉游shit_b.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.GEN.setObjectName("GEN")
        self.HK3 = QtWidgets.QPushButton(self.widget)
        self.HK3.setGeometry(QtCore.QRect(0, 130, 85, 90))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(16)
        self.HK3.setFont(font)
        self.HK3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HK3.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;background-image: url(:/新前缀/蕉游shit_b.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.HK3.setObjectName("HK3")
        self.KSP = QtWidgets.QPushButton(self.widget)
        self.KSP.setGeometry(QtCore.QRect(85, 130, 85, 91))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(13)
        self.KSP.setFont(font)
        self.KSP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.KSP.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;\n"
";\n"
"    background-image: url(:/新前缀/Exec_Node.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.KSP.setObjectName("KSP")
        self.OBSG = QtWidgets.QPushButton(self.widget)
        self.OBSG.setGeometry(QtCore.QRect(0, 220, 85, 91))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.OBSG.setFont(font)
        self.OBSG.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OBSG.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;\n"
";\n"
"    background-image: url(:/新前缀/Exec_Node.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.OBSG.setObjectName("OBSG")
        self.widget_3 = QtWidgets.QWidget(self.left_control)
        self.widget_3.setGeometry(QtCore.QRect(0, 350, 170, 381))
        self.widget_3.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.widget_3.setObjectName("widget_3")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"\n"
"border-bottom: 2px solid;border-bottom-color: rgb(255, 255, 255);")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.Kun2 = QtWidgets.QPushButton(self.widget_3)
        self.Kun2.setGeometry(QtCore.QRect(0, 40, 85, 90))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(13)
        self.Kun2.setFont(font)
        self.Kun2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Kun2.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;    background-image: url(:/新前缀/VR_inf_b.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.Kun2.setObjectName("Kun2")
        self.RtRES = QtWidgets.QPushButton(self.widget_3)
        self.RtRES.setGeometry(QtCore.QRect(85, 40, 85, 90))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(13)
        self.RtRES.setFont(font)
        self.RtRES.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RtRES.setStyleSheet("QPushButton{background-color: rgba(0, 0, 0, 0);background-size:40px;border: 2px solid #FF0000;border-color: rgba(255, 255, 255, 0);background-position:top;    background-image: url(:/新前缀/VR_inf_b.png);\n"
"background-repeat:no-repeat;\n"
"background-origin:content;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"        background-color: rgba(255, 85, 255, 120);\n"
"    transition: border-color 0.5s;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgba(255, 170, 0, 120);\n"
"    transition: border-color 0.5s;\n"
"}")
        self.RtRES.setObjectName("RtRES")
        self.banana = QtWidgets.QLabel(self.widget_2)
        self.banana.setGeometry(QtCore.QRect(1206, 81, 181, 191))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.banana.setFont(font)
        self.banana.setStyleSheet("")
        self.banana.setText("")
        self.banana.setPixmap(QtGui.QPixmap("banana.png"))
        self.banana.setAlignment(QtCore.Qt.AlignCenter)
        self.banana.setObjectName("banana")
        self.banana_2 = QtWidgets.QLabel(self.widget_2)
        self.banana_2.setGeometry(QtCore.QRect(1189, 150, 191, 41))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.banana_2.setFont(font)
        self.banana_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.banana_2.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_2.setObjectName("banana_2")
        self.banana_3 = QtWidgets.QLabel(self.widget_2)
        self.banana_3.setGeometry(QtCore.QRect(1189, 219, 191, 41))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.banana_3.setFont(font)
        self.banana_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.banana_3.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_3.setObjectName("banana_3")
        self.banana_5 = QtWidgets.QLabel(self.widget_2)
        self.banana_5.setGeometry(QtCore.QRect(1169, 350, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.banana_5.setFont(font)
        self.banana_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.banana_5.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_5.setObjectName("banana_5")
        self.banana_4 = QtWidgets.QLabel(self.widget_2)
        self.banana_4.setGeometry(QtCore.QRect(1210, 283, 175, 186))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.banana_4.sizePolicy().hasHeightForWidth())
        self.banana_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(14)
        self.banana_4.setFont(font)
        self.banana_4.setStyleSheet("")
        self.banana_4.setText("")
        self.banana_4.setPixmap(QtGui.QPixmap("蕉基百科.PNG"))
        self.banana_4.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_4.setObjectName("banana_4")
        self.banana_6 = QtWidgets.QLabel(self.widget_2)
        self.banana_6.setGeometry(QtCore.QRect(1189, 416, 191, 41))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(11)
        self.banana_6.setFont(font)
        self.banana_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.banana_6.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_6.setObjectName("banana_6")
        self.banana_7 = QtWidgets.QLabel(self.widget_2)
        self.banana_7.setGeometry(QtCore.QRect(1169, 484, 211, 41))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(11)
        self.banana_7.setFont(font)
        self.banana_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.banana_7.setAlignment(QtCore.Qt.AlignCenter)
        self.banana_7.setObjectName("banana_7")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setGeometry(QtCore.QRect(225, 650, 791, 26))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(16)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"      border:none;   /*无边框*/\n"
"        background-color: rgba(193, 193, 193, 100);\n"
"      border-radius:5px;\n"
"        /*文本颜色*/\n"
"    color: rgb(245, 71, 251);\n"
"}\n"
" \n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: rgba(0, 255, 213, 105);\n"
"      border-radius:4px;\n"
"}")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 63)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.Pro = QtWidgets.QLabel(self.widget_2)
        self.Pro.setGeometry(QtCore.QRect(225, 614, 781, 31))
        font = QtGui.QFont()
        font.setFamily("华光钢铁直黑 可变体 Medium")
        font.setPointSize(21)
        self.Pro.setFont(font)
        self.Pro.setStyleSheet("color: rgba(247, 0, 255, 180);")
        self.Pro.setObjectName("Pro")
        self.label_3.raise_()
        self.Head.raise_()
        self.widget_4.raise_()
        self.widget_5.raise_()
        self.widget_6.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.left_control.raise_()
        self.banana.raise_()
        self.banana_2.raise_()
        self.banana_3.raise_()
        self.banana_4.raise_()
        self.banana_5.raise_()
        self.banana_6.raise_()
        self.banana_7.raise_()
        self.progressBar.raise_()
        self.Pro.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "蕉坏：性穷铁蛋"))
        self.label_5.setText(_translate("Form", "1.5.0"))
        self.label_6.setText(_translate("Form", "V-Radiotion集合程序"))
        self.pushButton_13.setText(_translate("Form", "X"))
        self.pushButton_15.setText(_translate("Form", "♂"))
        self.pushButton_14.setText(_translate("Form", "-"))
        self.pushButton_11.setText(_translate("Form", "开始♂游戏"))
        self.label_7.setText(_translate("Form", "程序列表"))
        self.label_8.setText(_translate("Form", "游戏启动器"))
        self.SR.setText(_translate("Form", "\n"
"\n"
"蕉坏♂\n"
"性穷铁道"))
        self.GEN.setText(_translate("Form", "\n"
"\n"
"蕉♂神"))
        self.HK3.setText(_translate("Form", "\n"
"\n"
"蕉♂坏3"))
        self.KSP.setText(_translate("Form", "\n"
"\n"
"KSP-64"))
        self.OBSG.setText(_translate("Form", "\n"
"\n"
"通用\n"
"启动器"))
        self.label_9.setText(_translate("Form", "V-Radiotion程序"))
        self.Kun2.setText(_translate("Form", "\n"
"\n"
"鲲鲲2"))
        self.RtRES.setText(_translate("Form", "\n"
"\n"
"辐射组\n"
"管理程序"))
        self.banana_2.setText(_translate("Form", "点击前往星铁小助手"))
        self.banana_3.setText(_translate("Form", "点击前往星铁微博"))
        self.banana_5.setText(_translate("Form", "点击加入星铁官方QQ群"))
        self.banana_6.setText(_translate("Form", "程序员自己解决启动器问题"))
        self.banana_7.setText(_translate("Form", "V-Radiation集合程序操作手册"))
        self.Pro.setText(_translate("Form", "进程名字"))
import 按键图片_rc
